export { default as Tutorials } from "./Tutorials";
export { default as Home } from "./Home";
export { default as Controls } from "./Controls";
export { default as History } from "./History";
export { default as About } from "./About";
export { default as Leaderboard } from "./Leaderboard";
export { default as Credits } from "./Credits";
export { default as Scoring } from "./Scoring";
export { default as Bugs } from "./Bugs";
